# Generated by Django 3.0.6 on 2020-05-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200530_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeID', models.CharField(max_length=200)),
                ('EmployeeName', models.CharField(max_length=200)),
                ('EmployeeDesignation', models.CharField(max_length=200)),
                ('Group', models.CharField(max_length=200)),
                ('soc', models.CharField(max_length=200)),
                ('moc', models.CharField(max_length=200)),
                ('wow', models.CharField(max_length=200)),
                ('dow', models.CharField(max_length=200)),
                ('ho', models.CharField(max_length=200)),
                ('hi', models.CharField(max_length=200)),
                ('boe', models.CharField(max_length=200)),
                ('bow', models.CharField(max_length=200)),
                ('love', models.CharField(max_length=200)),
                ('ka', models.CharField(max_length=200)),
                ('mano', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=200)),
                ('surya', models.CharField(max_length=200)),
                ('lov', models.CharField(max_length=200)),
                ('sathya', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
